### PR TITLE
clean-up queue consumer, logger

### PR DESCRIPTION
**Pull request by PuerkitoBio**

### CODE REVIEW

**Comment by jharlap** [comment]
Test is failing because of godep having outdated AWS lib but PR depends on newer AWS lib. Mind updating the godep?

**Comment by PuerkitoBio** [comment]
There you go, `godep go test ./...` was green for me.

**Comment by jharlap** [comment]
Ironically, removing godep (because it's not good practice for a library to vendor its deps) and goconvey in another PR, making that last change unnecessary - but I appreciate that you did it anyway ;)

Will cherry pick the first commit in once I merge #10

**Comment by jharlap** [comment]
rebased and cherry-picked in #11, so closing this.

**Pull request closed without merging**
